with:
  github-token: ${{ github.token }}
  leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
  leetcode-session: ${{ secrets.LEETCODE_SESSION }}
  destination-folder: solutions # Optional: puts code in a specific folder
